version: '3.4'

services:
  sampleproject:
    image: tennismanager-vite
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000