services:
  reverse-proxy:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--providers.docker"
    ports:
      - "80:80"
      # Web UI Enabled by --api.insecure=true
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tennismanager-vite:
    image: tennismanager-vite
    labels:
      # Eventually change this to your domain
      - "traefik.http.routers.tennismanager-vite.rule=Host(`tennismanager.local`)"
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production